### ISSUE TITLE
Make a menu item for this autocrop script

### ISSUE THREAD

**Issue by timbowman** [timbowman/tb.nuke#24]
nukescripts.autocrop(first=None, last=None, inc=None, layer="rgba")

from: https://magicbeansvfx.wordpress.com/2015/07/27/nukes-hidden-autocrop-script/

**Comment by MagicBeansVFX** [comment]
Hi Tim,  I've updated my post on Magic Beans to include such a thing. Hope your well. J

**Comment by timbowman** [comment]
@MagicBeansVFX 
That's killer. Thanks Jack!

**Comment by timbowman** [comment]
10cb7f3
